-- ============================================================
-- V1：初始建表 —— 创建 tasks（任务表）
-- 命名规则：V<版本号>__<描述>.sql
-- Flyway 启动时按版本号顺序执行，已执行过的不会重复执行
-- ============================================================

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    task_type   VARCHAR(255),
    input_text  TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    result      TEXT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);
