-- ============================================================
-- V2：用户表 + 任务关联
-- ============================================================

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(20) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP
);

-- 给 tasks 加 user_id 外键
ALTER TABLE tasks ADD COLUMN user_id BIGINT;
ALTER TABLE tasks ADD CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES users(id);