-- ============================================================
-- V3：AI 调用日志表
-- ============================================================

CREATE TABLE ai_usage_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         BIGINT,
    provider        VARCHAR(20) NOT NULL,
    model_name      VARCHAR(50),
    tokens_used     INT DEFAULT 0,
    elapsed_ms      BIGINT DEFAULT 0,
    request_preview TEXT,
    created_at      TIMESTAMP
);
