-- V7：对话系统 —— 多轮对话支持

CREATE TABLE conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    user_id     BIGINT,
    created_at  TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL,
    role             VARCHAR(20) NOT NULL,
    content          TEXT NOT NULL,
    created_at       TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id)
);
